// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	service "github.com/e2engine/cli/internal/service"
	model "github.com/e2engine/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockinternalService is a mock of internalService interface.
type MockinternalService struct {
	ctrl     *gomock.Controller
	recorder *MockinternalServiceMockRecorder
	isgomock struct{}
}

// MockinternalServiceMockRecorder is the mock recorder for MockinternalService.
type MockinternalServiceMockRecorder struct {
	mock *MockinternalService
}

// NewMockinternalService creates a new mock instance.
func NewMockinternalService(ctrl *gomock.Controller) *MockinternalService {
	mock := &MockinternalService{ctrl: ctrl}
	mock.recorder = &MockinternalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinternalService) EXPECT() *MockinternalServiceMockRecorder {
	return m.recorder
}

// CreateTest mocks base method.
func (m *MockinternalService) CreateTest(ctx context.Context, specPath string) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTest", ctx, specPath)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTest indicates an expected call of CreateTest.
func (mr *MockinternalServiceMockRecorder) CreateTest(ctx, specPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTest", reflect.TypeOf((*MockinternalService)(nil).CreateTest), ctx, specPath)
}

// DeleteTest mocks base method.
func (m *MockinternalService) DeleteTest(ctx context.Context, ref string) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTest", ctx, ref)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTest indicates an expected call of DeleteTest.
func (mr *MockinternalServiceMockRecorder) DeleteTest(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTest", reflect.TypeOf((*MockinternalService)(nil).DeleteTest), ctx, ref)
}

// GetTest mocks base method.
func (m *MockinternalService) GetTest(ctx context.Context, ref string) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", ctx, ref)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTest indicates an expected call of GetTest.
func (mr *MockinternalServiceMockRecorder) GetTest(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockinternalService)(nil).GetTest), ctx, ref)
}

// ListTests mocks base method.
func (m *MockinternalService) ListTests(ctx context.Context, params *service.ListTestsParams) ([]model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTests", ctx, params)
	ret0, _ := ret[0].([]model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTests indicates an expected call of ListTests.
func (mr *MockinternalServiceMockRecorder) ListTests(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTests", reflect.TypeOf((*MockinternalService)(nil).ListTests), ctx, params)
}

// RunTest mocks base method.
func (m *MockinternalService) RunTest(ctx context.Context, environmentRef, testRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTest", ctx, environmentRef, testRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTest indicates an expected call of RunTest.
func (mr *MockinternalServiceMockRecorder) RunTest(ctx, environmentRef, testRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTest", reflect.TypeOf((*MockinternalService)(nil).RunTest), ctx, environmentRef, testRef)
}

// ValidateTest mocks base method.
func (m *MockinternalService) ValidateTest(ctx context.Context, specPath string) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTest", ctx, specPath)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateTest indicates an expected call of ValidateTest.
func (mr *MockinternalServiceMockRecorder) ValidateTest(ctx, specPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTest", reflect.TypeOf((*MockinternalService)(nil).ValidateTest), ctx, specPath)
}
