// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=testsuiteexecution
//

// Package testsuiteexecution is a generated GoMock package.
package testsuiteexecution

import (
	context "context"
	reflect "reflect"

	service "github.com/e2engine/cli/internal/service"
	model "github.com/e2engine/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockinternalService is a mock of internalService interface.
type MockinternalService struct {
	ctrl     *gomock.Controller
	recorder *MockinternalServiceMockRecorder
	isgomock struct{}
}

// MockinternalServiceMockRecorder is the mock recorder for MockinternalService.
type MockinternalServiceMockRecorder struct {
	mock *MockinternalService
}

// NewMockinternalService creates a new mock instance.
func NewMockinternalService(ctrl *gomock.Controller) *MockinternalService {
	mock := &MockinternalService{ctrl: ctrl}
	mock.recorder = &MockinternalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinternalService) EXPECT() *MockinternalServiceMockRecorder {
	return m.recorder
}

// DeleteTestSuiteExecution mocks base method.
func (m *MockinternalService) DeleteTestSuiteExecution(ctx context.Context, ref string) (*model.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestSuiteExecution", ctx, ref)
	ret0, _ := ret[0].(*model.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTestSuiteExecution indicates an expected call of DeleteTestSuiteExecution.
func (mr *MockinternalServiceMockRecorder) DeleteTestSuiteExecution(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestSuiteExecution", reflect.TypeOf((*MockinternalService)(nil).DeleteTestSuiteExecution), ctx, ref)
}

// GetTestSuiteExecution mocks base method.
func (m *MockinternalService) GetTestSuiteExecution(ctx context.Context, ref string) (*model.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuiteExecution", ctx, ref)
	ret0, _ := ret[0].(*model.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuiteExecution indicates an expected call of GetTestSuiteExecution.
func (mr *MockinternalServiceMockRecorder) GetTestSuiteExecution(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuiteExecution", reflect.TypeOf((*MockinternalService)(nil).GetTestSuiteExecution), ctx, ref)
}

// GetTestSuiteExecutionStatus mocks base method.
func (m *MockinternalService) GetTestSuiteExecutionStatus(ctx context.Context, ref string) (model.ExecutionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuiteExecutionStatus", ctx, ref)
	ret0, _ := ret[0].(model.ExecutionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuiteExecutionStatus indicates an expected call of GetTestSuiteExecutionStatus.
func (mr *MockinternalServiceMockRecorder) GetTestSuiteExecutionStatus(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuiteExecutionStatus", reflect.TypeOf((*MockinternalService)(nil).GetTestSuiteExecutionStatus), ctx, ref)
}

// ListTestSuiteExecutions mocks base method.
func (m *MockinternalService) ListTestSuiteExecutions(ctx context.Context, params *service.ListTestSuiteExecutionsParams) ([]model.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestSuiteExecutions", ctx, params)
	ret0, _ := ret[0].([]model.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTestSuiteExecutions indicates an expected call of ListTestSuiteExecutions.
func (mr *MockinternalServiceMockRecorder) ListTestSuiteExecutions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestSuiteExecutions", reflect.TypeOf((*MockinternalService)(nil).ListTestSuiteExecutions), ctx, params)
}
