// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=testexecution
//

// Package testexecution is a generated GoMock package.
package testexecution

import (
	context "context"
	reflect "reflect"

	service "github.com/e2engine/cli/internal/service"
	model "github.com/e2engine/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockinternalService is a mock of internalService interface.
type MockinternalService struct {
	ctrl     *gomock.Controller
	recorder *MockinternalServiceMockRecorder
	isgomock struct{}
}

// MockinternalServiceMockRecorder is the mock recorder for MockinternalService.
type MockinternalServiceMockRecorder struct {
	mock *MockinternalService
}

// NewMockinternalService creates a new mock instance.
func NewMockinternalService(ctrl *gomock.Controller) *MockinternalService {
	mock := &MockinternalService{ctrl: ctrl}
	mock.recorder = &MockinternalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinternalService) EXPECT() *MockinternalServiceMockRecorder {
	return m.recorder
}

// DeleteTestExecution mocks base method.
func (m *MockinternalService) DeleteTestExecution(ctx context.Context, ref string) (*model.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestExecution", ctx, ref)
	ret0, _ := ret[0].(*model.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTestExecution indicates an expected call of DeleteTestExecution.
func (mr *MockinternalServiceMockRecorder) DeleteTestExecution(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestExecution", reflect.TypeOf((*MockinternalService)(nil).DeleteTestExecution), ctx, ref)
}

// GetTestExecution mocks base method.
func (m *MockinternalService) GetTestExecution(ctx context.Context, ref string) (*model.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestExecution", ctx, ref)
	ret0, _ := ret[0].(*model.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestExecution indicates an expected call of GetTestExecution.
func (mr *MockinternalServiceMockRecorder) GetTestExecution(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestExecution", reflect.TypeOf((*MockinternalService)(nil).GetTestExecution), ctx, ref)
}

// GetTestExecutionStatus mocks base method.
func (m *MockinternalService) GetTestExecutionStatus(ctx context.Context, ref string) (model.ExecutionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestExecutionStatus", ctx, ref)
	ret0, _ := ret[0].(model.ExecutionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestExecutionStatus indicates an expected call of GetTestExecutionStatus.
func (mr *MockinternalServiceMockRecorder) GetTestExecutionStatus(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestExecutionStatus", reflect.TypeOf((*MockinternalService)(nil).GetTestExecutionStatus), ctx, ref)
}

// ListTestExecutions mocks base method.
func (m *MockinternalService) ListTestExecutions(ctx context.Context, params *service.ListTestExecutionsParams) ([]model.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestExecutions", ctx, params)
	ret0, _ := ret[0].([]model.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTestExecutions indicates an expected call of ListTestExecutions.
func (mr *MockinternalServiceMockRecorder) ListTestExecutions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestExecutions", reflect.TypeOf((*MockinternalService)(nil).ListTestExecutions), ctx, params)
}
