// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=environment
//

// Package environment is a generated GoMock package.
package environment

import (
	context "context"
	reflect "reflect"

	service "github.com/e2engine/cli/internal/service"
	model "github.com/e2engine/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockinternalService is a mock of internalService interface.
type MockinternalService struct {
	ctrl     *gomock.Controller
	recorder *MockinternalServiceMockRecorder
	isgomock struct{}
}

// MockinternalServiceMockRecorder is the mock recorder for MockinternalService.
type MockinternalServiceMockRecorder struct {
	mock *MockinternalService
}

// NewMockinternalService creates a new mock instance.
func NewMockinternalService(ctrl *gomock.Controller) *MockinternalService {
	mock := &MockinternalService{ctrl: ctrl}
	mock.recorder = &MockinternalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinternalService) EXPECT() *MockinternalServiceMockRecorder {
	return m.recorder
}

// CreateEnvironment mocks base method.
func (m *MockinternalService) CreateEnvironment(ctx context.Context, specPath string) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironment", ctx, specPath)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironment indicates an expected call of CreateEnvironment.
func (mr *MockinternalServiceMockRecorder) CreateEnvironment(ctx, specPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironment", reflect.TypeOf((*MockinternalService)(nil).CreateEnvironment), ctx, specPath)
}

// DeleteEnvironment mocks base method.
func (m *MockinternalService) DeleteEnvironment(ctx context.Context, ref string) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironment", ctx, ref)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEnvironment indicates an expected call of DeleteEnvironment.
func (mr *MockinternalServiceMockRecorder) DeleteEnvironment(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironment", reflect.TypeOf((*MockinternalService)(nil).DeleteEnvironment), ctx, ref)
}

// GetEnvironment mocks base method.
func (m *MockinternalService) GetEnvironment(ctx context.Context, ref string) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", ctx, ref)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment.
func (mr *MockinternalServiceMockRecorder) GetEnvironment(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*MockinternalService)(nil).GetEnvironment), ctx, ref)
}

// ListEnvironments mocks base method.
func (m *MockinternalService) ListEnvironments(ctx context.Context, params *service.ListEnvironmentsParams) ([]model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironments", ctx, params)
	ret0, _ := ret[0].([]model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnvironments indicates an expected call of ListEnvironments.
func (mr *MockinternalServiceMockRecorder) ListEnvironments(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironments", reflect.TypeOf((*MockinternalService)(nil).ListEnvironments), ctx, params)
}

// ValidateEnvironment mocks base method.
func (m *MockinternalService) ValidateEnvironment(ctx context.Context, specPath string) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEnvironment", ctx, specPath)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateEnvironment indicates an expected call of ValidateEnvironment.
func (mr *MockinternalServiceMockRecorder) ValidateEnvironment(ctx, specPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEnvironment", reflect.TypeOf((*MockinternalService)(nil).ValidateEnvironment), ctx, specPath)
}
