// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=service RunnerService,runnerLauncher
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	core "github.com/e2engine/core/api"
	execute "github.com/e2engine/core/execute"
	model "github.com/e2engine/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockcoreService is a mock of coreService interface.
type MockcoreService struct {
	ctrl     *gomock.Controller
	recorder *MockcoreServiceMockRecorder
	isgomock struct{}
}

// MockcoreServiceMockRecorder is the mock recorder for MockcoreService.
type MockcoreServiceMockRecorder struct {
	mock *MockcoreService
}

// NewMockcoreService creates a new mock instance.
func NewMockcoreService(ctrl *gomock.Controller) *MockcoreService {
	mock := &MockcoreService{ctrl: ctrl}
	mock.recorder = &MockcoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcoreService) EXPECT() *MockcoreServiceMockRecorder {
	return m.recorder
}

// CreateEnvironment mocks base method.
func (m *MockcoreService) CreateEnvironment(ctx context.Context, params *core.CreateEnvironmentParams) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironment", ctx, params)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironment indicates an expected call of CreateEnvironment.
func (mr *MockcoreServiceMockRecorder) CreateEnvironment(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironment", reflect.TypeOf((*MockcoreService)(nil).CreateEnvironment), ctx, params)
}

// CreateTest mocks base method.
func (m *MockcoreService) CreateTest(ctx context.Context, params *core.CreateTestParams) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTest", ctx, params)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTest indicates an expected call of CreateTest.
func (mr *MockcoreServiceMockRecorder) CreateTest(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTest", reflect.TypeOf((*MockcoreService)(nil).CreateTest), ctx, params)
}

// CreateTestSuite mocks base method.
func (m *MockcoreService) CreateTestSuite(ctx context.Context, params *core.CreateTestSuiteParams) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestSuite", ctx, params)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTestSuite indicates an expected call of CreateTestSuite.
func (mr *MockcoreServiceMockRecorder) CreateTestSuite(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestSuite", reflect.TypeOf((*MockcoreService)(nil).CreateTestSuite), ctx, params)
}

// DeleteEnvironment mocks base method.
func (m *MockcoreService) DeleteEnvironment(ctx context.Context, prefix string) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironment", ctx, prefix)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEnvironment indicates an expected call of DeleteEnvironment.
func (mr *MockcoreServiceMockRecorder) DeleteEnvironment(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironment", reflect.TypeOf((*MockcoreService)(nil).DeleteEnvironment), ctx, prefix)
}

// DeleteTest mocks base method.
func (m *MockcoreService) DeleteTest(ctx context.Context, prefix string) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTest", ctx, prefix)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTest indicates an expected call of DeleteTest.
func (mr *MockcoreServiceMockRecorder) DeleteTest(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTest", reflect.TypeOf((*MockcoreService)(nil).DeleteTest), ctx, prefix)
}

// DeleteTestExecution mocks base method.
func (m *MockcoreService) DeleteTestExecution(ctx context.Context, prefix string) (*model.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestExecution", ctx, prefix)
	ret0, _ := ret[0].(*model.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTestExecution indicates an expected call of DeleteTestExecution.
func (mr *MockcoreServiceMockRecorder) DeleteTestExecution(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestExecution", reflect.TypeOf((*MockcoreService)(nil).DeleteTestExecution), ctx, prefix)
}

// DeleteTestSuite mocks base method.
func (m *MockcoreService) DeleteTestSuite(ctx context.Context, prefix string) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestSuite", ctx, prefix)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTestSuite indicates an expected call of DeleteTestSuite.
func (mr *MockcoreServiceMockRecorder) DeleteTestSuite(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestSuite", reflect.TypeOf((*MockcoreService)(nil).DeleteTestSuite), ctx, prefix)
}

// DeleteTestSuiteExecution mocks base method.
func (m *MockcoreService) DeleteTestSuiteExecution(ctx context.Context, prefix string) (*model.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestSuiteExecution", ctx, prefix)
	ret0, _ := ret[0].(*model.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTestSuiteExecution indicates an expected call of DeleteTestSuiteExecution.
func (mr *MockcoreServiceMockRecorder) DeleteTestSuiteExecution(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestSuiteExecution", reflect.TypeOf((*MockcoreService)(nil).DeleteTestSuiteExecution), ctx, prefix)
}

// GetEnvironment mocks base method.
func (m *MockcoreService) GetEnvironment(ctx context.Context, ref string) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", ctx, ref)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment.
func (mr *MockcoreServiceMockRecorder) GetEnvironment(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*MockcoreService)(nil).GetEnvironment), ctx, ref)
}

// GetEnvironmentsPage mocks base method.
func (m *MockcoreService) GetEnvironmentsPage(ctx context.Context, params *core.GetEnvironmentsPageParams) (*model.EnvironmentsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentsPage", ctx, params)
	ret0, _ := ret[0].(*model.EnvironmentsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentsPage indicates an expected call of GetEnvironmentsPage.
func (mr *MockcoreServiceMockRecorder) GetEnvironmentsPage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentsPage", reflect.TypeOf((*MockcoreService)(nil).GetEnvironmentsPage), ctx, params)
}

// GetTest mocks base method.
func (m *MockcoreService) GetTest(ctx context.Context, ref string) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", ctx, ref)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTest indicates an expected call of GetTest.
func (mr *MockcoreServiceMockRecorder) GetTest(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockcoreService)(nil).GetTest), ctx, ref)
}

// GetTestExecution mocks base method.
func (m *MockcoreService) GetTestExecution(ctx context.Context, ref string) (*model.TestExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestExecution", ctx, ref)
	ret0, _ := ret[0].(*model.TestExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestExecution indicates an expected call of GetTestExecution.
func (mr *MockcoreServiceMockRecorder) GetTestExecution(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestExecution", reflect.TypeOf((*MockcoreService)(nil).GetTestExecution), ctx, ref)
}

// GetTestExecutionStatus mocks base method.
func (m *MockcoreService) GetTestExecutionStatus(ctx context.Context, ref string) (model.ExecutionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestExecutionStatus", ctx, ref)
	ret0, _ := ret[0].(model.ExecutionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestExecutionStatus indicates an expected call of GetTestExecutionStatus.
func (mr *MockcoreServiceMockRecorder) GetTestExecutionStatus(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestExecutionStatus", reflect.TypeOf((*MockcoreService)(nil).GetTestExecutionStatus), ctx, ref)
}

// GetTestExecutionsPage mocks base method.
func (m *MockcoreService) GetTestExecutionsPage(ctx context.Context, params *core.GetTestExecutionsPageParams) (*model.TestExecutionsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestExecutionsPage", ctx, params)
	ret0, _ := ret[0].(*model.TestExecutionsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestExecutionsPage indicates an expected call of GetTestExecutionsPage.
func (mr *MockcoreServiceMockRecorder) GetTestExecutionsPage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestExecutionsPage", reflect.TypeOf((*MockcoreService)(nil).GetTestExecutionsPage), ctx, params)
}

// GetTestSuite mocks base method.
func (m *MockcoreService) GetTestSuite(ctx context.Context, ref string) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuite", ctx, ref)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuite indicates an expected call of GetTestSuite.
func (mr *MockcoreServiceMockRecorder) GetTestSuite(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuite", reflect.TypeOf((*MockcoreService)(nil).GetTestSuite), ctx, ref)
}

// GetTestSuiteExecution mocks base method.
func (m *MockcoreService) GetTestSuiteExecution(ctx context.Context, ref string) (*model.TestSuiteExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuiteExecution", ctx, ref)
	ret0, _ := ret[0].(*model.TestSuiteExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuiteExecution indicates an expected call of GetTestSuiteExecution.
func (mr *MockcoreServiceMockRecorder) GetTestSuiteExecution(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuiteExecution", reflect.TypeOf((*MockcoreService)(nil).GetTestSuiteExecution), ctx, ref)
}

// GetTestSuiteExecutionStatus mocks base method.
func (m *MockcoreService) GetTestSuiteExecutionStatus(ctx context.Context, ref string) (model.ExecutionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuiteExecutionStatus", ctx, ref)
	ret0, _ := ret[0].(model.ExecutionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuiteExecutionStatus indicates an expected call of GetTestSuiteExecutionStatus.
func (mr *MockcoreServiceMockRecorder) GetTestSuiteExecutionStatus(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuiteExecutionStatus", reflect.TypeOf((*MockcoreService)(nil).GetTestSuiteExecutionStatus), ctx, ref)
}

// GetTestSuiteExecutionsPage mocks base method.
func (m *MockcoreService) GetTestSuiteExecutionsPage(ctx context.Context, params *core.GetTestSuiteExecutionsPageParams) (*model.TestSuiteExecutionsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuiteExecutionsPage", ctx, params)
	ret0, _ := ret[0].(*model.TestSuiteExecutionsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuiteExecutionsPage indicates an expected call of GetTestSuiteExecutionsPage.
func (mr *MockcoreServiceMockRecorder) GetTestSuiteExecutionsPage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuiteExecutionsPage", reflect.TypeOf((*MockcoreService)(nil).GetTestSuiteExecutionsPage), ctx, params)
}

// GetTestSuitesPage mocks base method.
func (m *MockcoreService) GetTestSuitesPage(ctx context.Context, params *core.GetTestSuitesPageParams) (*model.TestSuitesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuitesPage", ctx, params)
	ret0, _ := ret[0].(*model.TestSuitesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuitesPage indicates an expected call of GetTestSuitesPage.
func (mr *MockcoreServiceMockRecorder) GetTestSuitesPage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuitesPage", reflect.TypeOf((*MockcoreService)(nil).GetTestSuitesPage), ctx, params)
}

// GetTestsPage mocks base method.
func (m *MockcoreService) GetTestsPage(ctx context.Context, params *core.GetTestsPageParams) (*model.TestsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestsPage", ctx, params)
	ret0, _ := ret[0].(*model.TestsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestsPage indicates an expected call of GetTestsPage.
func (mr *MockcoreServiceMockRecorder) GetTestsPage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestsPage", reflect.TypeOf((*MockcoreService)(nil).GetTestsPage), ctx, params)
}

// RunTest mocks base method.
func (m *MockcoreService) RunTest(ctx context.Context, params core.TestRunRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTest", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTest indicates an expected call of RunTest.
func (mr *MockcoreServiceMockRecorder) RunTest(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTest", reflect.TypeOf((*MockcoreService)(nil).RunTest), ctx, params)
}

// RunTestSuite mocks base method.
func (m *MockcoreService) RunTestSuite(ctx context.Context, params core.TestSuiteRunRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTestSuite", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTestSuite indicates an expected call of RunTestSuite.
func (mr *MockcoreServiceMockRecorder) RunTestSuite(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTestSuite", reflect.TypeOf((*MockcoreService)(nil).RunTestSuite), ctx, params)
}

// ValidateEnvironment mocks base method.
func (m *MockcoreService) ValidateEnvironment(ctx context.Context, env *model.Environment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEnvironment", ctx, env)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateEnvironment indicates an expected call of ValidateEnvironment.
func (mr *MockcoreServiceMockRecorder) ValidateEnvironment(ctx, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEnvironment", reflect.TypeOf((*MockcoreService)(nil).ValidateEnvironment), ctx, env)
}

// ValidateTest mocks base method.
func (m *MockcoreService) ValidateTest(ctx context.Context, test *model.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTest", ctx, test)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTest indicates an expected call of ValidateTest.
func (mr *MockcoreServiceMockRecorder) ValidateTest(ctx, test any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTest", reflect.TypeOf((*MockcoreService)(nil).ValidateTest), ctx, test)
}

// ValidateTestSuite mocks base method.
func (m *MockcoreService) ValidateTestSuite(ctx context.Context, ts *model.TestSuite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTestSuite", ctx, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTestSuite indicates an expected call of ValidateTestSuite.
func (mr *MockcoreServiceMockRecorder) ValidateTestSuite(ctx, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTestSuite", reflect.TypeOf((*MockcoreService)(nil).ValidateTestSuite), ctx, ts)
}

// MockRunnerService is a mock of RunnerService interface.
type MockRunnerService struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerServiceMockRecorder
	isgomock struct{}
}

// MockRunnerServiceMockRecorder is the mock recorder for MockRunnerService.
type MockRunnerServiceMockRecorder struct {
	mock *MockRunnerService
}

// NewMockRunnerService creates a new mock instance.
func NewMockRunnerService(ctrl *gomock.Controller) *MockRunnerService {
	mock := &MockRunnerService{ctrl: ctrl}
	mock.recorder = &MockRunnerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnerService) EXPECT() *MockRunnerServiceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockRunnerService) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRunnerServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunnerService)(nil).Run), ctx)
}

// StartTestExecution mocks base method.
func (m *MockRunnerService) StartTestExecution(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTestExecution", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTestExecution indicates an expected call of StartTestExecution.
func (mr *MockRunnerServiceMockRecorder) StartTestExecution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTestExecution", reflect.TypeOf((*MockRunnerService)(nil).StartTestExecution), ctx)
}

// MockschedulerService is a mock of schedulerService interface.
type MockschedulerService struct {
	ctrl     *gomock.Controller
	recorder *MockschedulerServiceMockRecorder
	isgomock struct{}
}

// MockschedulerServiceMockRecorder is the mock recorder for MockschedulerService.
type MockschedulerServiceMockRecorder struct {
	mock *MockschedulerService
}

// NewMockschedulerService creates a new mock instance.
func NewMockschedulerService(ctrl *gomock.Controller) *MockschedulerService {
	mock := &MockschedulerService{ctrl: ctrl}
	mock.recorder = &MockschedulerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockschedulerService) EXPECT() *MockschedulerServiceMockRecorder {
	return m.recorder
}

// PublishTestJob mocks base method.
func (m *MockschedulerService) PublishTestJob(ctx context.Context, job execute.TestJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTestJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTestJob indicates an expected call of PublishTestJob.
func (mr *MockschedulerServiceMockRecorder) PublishTestJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTestJob", reflect.TypeOf((*MockschedulerService)(nil).PublishTestJob), ctx, job)
}

// MockstateUpdaterService is a mock of stateUpdaterService interface.
type MockstateUpdaterService struct {
	ctrl     *gomock.Controller
	recorder *MockstateUpdaterServiceMockRecorder
	isgomock struct{}
}

// MockstateUpdaterServiceMockRecorder is the mock recorder for MockstateUpdaterService.
type MockstateUpdaterServiceMockRecorder struct {
	mock *MockstateUpdaterService
}

// NewMockstateUpdaterService creates a new mock instance.
func NewMockstateUpdaterService(ctrl *gomock.Controller) *MockstateUpdaterService {
	mock := &MockstateUpdaterService{ctrl: ctrl}
	mock.recorder = &MockstateUpdaterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstateUpdaterService) EXPECT() *MockstateUpdaterServiceMockRecorder {
	return m.recorder
}

// SetTestCompleted mocks base method.
func (m *MockstateUpdaterService) SetTestCompleted(ctx context.Context, result execute.TestExecutionResult) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTestCompleted", ctx, result)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTestCompleted indicates an expected call of SetTestCompleted.
func (mr *MockstateUpdaterServiceMockRecorder) SetTestCompleted(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTestCompleted", reflect.TypeOf((*MockstateUpdaterService)(nil).SetTestCompleted), ctx, result)
}

// SetTestRunning mocks base method.
func (m *MockstateUpdaterService) SetTestRunning(ctx context.Context, executionID string, startedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTestRunning", ctx, executionID, startedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTestRunning indicates an expected call of SetTestRunning.
func (mr *MockstateUpdaterServiceMockRecorder) SetTestRunning(ctx, executionID, startedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTestRunning", reflect.TypeOf((*MockstateUpdaterService)(nil).SetTestRunning), ctx, executionID, startedAt)
}

// SetTestSuiteCompleted mocks base method.
func (m *MockstateUpdaterService) SetTestSuiteCompleted(ctx context.Context, result execute.TestSuiteExecutionResult) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTestSuiteCompleted", ctx, result)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTestSuiteCompleted indicates an expected call of SetTestSuiteCompleted.
func (mr *MockstateUpdaterServiceMockRecorder) SetTestSuiteCompleted(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTestSuiteCompleted", reflect.TypeOf((*MockstateUpdaterService)(nil).SetTestSuiteCompleted), ctx, result)
}

// SetTestSuiteRunning mocks base method.
func (m *MockstateUpdaterService) SetTestSuiteRunning(ctx context.Context, executionID string, startedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTestSuiteRunning", ctx, executionID, startedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTestSuiteRunning indicates an expected call of SetTestSuiteRunning.
func (mr *MockstateUpdaterServiceMockRecorder) SetTestSuiteRunning(ctx, executionID, startedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTestSuiteRunning", reflect.TypeOf((*MockstateUpdaterService)(nil).SetTestSuiteRunning), ctx, executionID, startedAt)
}

// MockrunnerLauncher is a mock of runnerLauncher interface.
type MockrunnerLauncher struct {
	ctrl     *gomock.Controller
	recorder *MockrunnerLauncherMockRecorder
	isgomock struct{}
}

// MockrunnerLauncherMockRecorder is the mock recorder for MockrunnerLauncher.
type MockrunnerLauncherMockRecorder struct {
	mock *MockrunnerLauncher
}

// NewMockrunnerLauncher creates a new mock instance.
func NewMockrunnerLauncher(ctrl *gomock.Controller) *MockrunnerLauncher {
	mock := &MockrunnerLauncher{ctrl: ctrl}
	mock.recorder = &MockrunnerLauncherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrunnerLauncher) EXPECT() *MockrunnerLauncherMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockrunnerLauncher) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockrunnerLauncherMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockrunnerLauncher)(nil).Start), ctx)
}

// Mockcloser is a mock of closer interface.
type Mockcloser struct {
	ctrl     *gomock.Controller
	recorder *MockcloserMockRecorder
	isgomock struct{}
}

// MockcloserMockRecorder is the mock recorder for Mockcloser.
type MockcloserMockRecorder struct {
	mock *Mockcloser
}

// NewMockcloser creates a new mock instance.
func NewMockcloser(ctrl *gomock.Controller) *Mockcloser {
	mock := &Mockcloser{ctrl: ctrl}
	mock.recorder = &MockcloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcloser) EXPECT() *MockcloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockcloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockcloserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockcloser)(nil).Close))
}
