// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service_test.go -package=testsuite
//

// Package testsuite is a generated GoMock package.
package testsuite

import (
	context "context"
	reflect "reflect"

	service "github.com/e2engine/cli/internal/service"
	model "github.com/e2engine/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockinternalService is a mock of internalService interface.
type MockinternalService struct {
	ctrl     *gomock.Controller
	recorder *MockinternalServiceMockRecorder
	isgomock struct{}
}

// MockinternalServiceMockRecorder is the mock recorder for MockinternalService.
type MockinternalServiceMockRecorder struct {
	mock *MockinternalService
}

// NewMockinternalService creates a new mock instance.
func NewMockinternalService(ctrl *gomock.Controller) *MockinternalService {
	mock := &MockinternalService{ctrl: ctrl}
	mock.recorder = &MockinternalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinternalService) EXPECT() *MockinternalServiceMockRecorder {
	return m.recorder
}

// CreateTestSuite mocks base method.
func (m *MockinternalService) CreateTestSuite(ctx context.Context, specPath string) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestSuite", ctx, specPath)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTestSuite indicates an expected call of CreateTestSuite.
func (mr *MockinternalServiceMockRecorder) CreateTestSuite(ctx, specPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestSuite", reflect.TypeOf((*MockinternalService)(nil).CreateTestSuite), ctx, specPath)
}

// DeleteTestSuite mocks base method.
func (m *MockinternalService) DeleteTestSuite(ctx context.Context, ref string) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTestSuite", ctx, ref)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTestSuite indicates an expected call of DeleteTestSuite.
func (mr *MockinternalServiceMockRecorder) DeleteTestSuite(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTestSuite", reflect.TypeOf((*MockinternalService)(nil).DeleteTestSuite), ctx, ref)
}

// GetTestSuite mocks base method.
func (m *MockinternalService) GetTestSuite(ctx context.Context, ref string) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSuite", ctx, ref)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestSuite indicates an expected call of GetTestSuite.
func (mr *MockinternalServiceMockRecorder) GetTestSuite(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSuite", reflect.TypeOf((*MockinternalService)(nil).GetTestSuite), ctx, ref)
}

// ListTestSuites mocks base method.
func (m *MockinternalService) ListTestSuites(ctx context.Context, params *service.ListTestSuitesParams) ([]model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestSuites", ctx, params)
	ret0, _ := ret[0].([]model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTestSuites indicates an expected call of ListTestSuites.
func (mr *MockinternalServiceMockRecorder) ListTestSuites(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestSuites", reflect.TypeOf((*MockinternalService)(nil).ListTestSuites), ctx, params)
}

// RunTestSuite mocks base method.
func (m *MockinternalService) RunTestSuite(ctx context.Context, environmentRef, testSuiteRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTestSuite", ctx, environmentRef, testSuiteRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTestSuite indicates an expected call of RunTestSuite.
func (mr *MockinternalServiceMockRecorder) RunTestSuite(ctx, environmentRef, testSuiteRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTestSuite", reflect.TypeOf((*MockinternalService)(nil).RunTestSuite), ctx, environmentRef, testSuiteRef)
}

// ValidateTestSuite mocks base method.
func (m *MockinternalService) ValidateTestSuite(ctx context.Context, specPath string) (*model.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTestSuite", ctx, specPath)
	ret0, _ := ret[0].(*model.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateTestSuite indicates an expected call of ValidateTestSuite.
func (mr *MockinternalServiceMockRecorder) ValidateTestSuite(ctx, specPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTestSuite", reflect.TypeOf((*MockinternalService)(nil).ValidateTestSuite), ctx, specPath)
}
